<a href="https://colab.research.google.com/github/redpineK/keras/blob/main/norm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Norm?

In linear algebra, functional analysis, and related areas of mathematics,  
a norm is a function that assigns a strictly positive length or size to each vector in a vector space (by wikipedia)

$$ \lVert x \rVert_p = ({\sum_{i=1}^{n} |x_i|^p})^\frac{1}{p} $$

# L1 Norm

Sum of Absolute values

$$ \lVert x \rVert_1 = ({\sum_{i=1}^{n} |x_i|}) $$

## example

Let's suppose we play game with dice.  
Dice has value of -3, -2, -1, 1, 2, 3  
positive number means you move forward according to the value  
negative number means you move backward according to the value

In [1]:
import pandas as pd
import numpy as np
from numpy import linalg

In [2]:
df = pd.DataFrame(np.random.randint(low=-3, high=3, size=(3, 3)))

In [3]:
df.columns=['move_1', 'move_2', 'move_3']

In [4]:
df.head()

move_1  move_2  move_3
0      -1      -1       0
1      -2      -3      -2
2       1      -3       1

### Who moved the most?

L1 norm can give you answer

In [5]:
movememts = df.values

In [6]:
movememts

array([[-1, -1,  0],
       [-2, -3, -2],
       [ 1, -3,  1]])

In [7]:
linalg.norm(movememts, ord=1,axis=1)

array([2., 7., 5.])

### L1 Norm  in Computer Science

- L1 Regularization
- Computer Vision

# L2 Norm

The l2 norm of a vector is the square root of the sum of the absolute values squared

$$ \lVert x \rVert_2 = ({\sum_{i=1}^{n} |x_i|^2})^\frac{1}{2} $$

## example

Let's suppose we want to get distance to the position in 2 dimensional space.

In [8]:
df = pd.DataFrame(np.random.randint(low=1, high=10, size=(3, 2)))

In [9]:
df.columns=['x', 'y']

In [ ]:
df.head()

x  y
0  9  4
1  7  3
2  9  9

In [10]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [11]:
# Create scatterplot of dataframe
sns.lmplot('x', # Horizontal axis
           'y', # Vertical axis
           data=df, # Data source
           fit_reg=False, # Don't fix a regression line
           scatter_kws={"s": 200}) # S marker size

# Set title
plt.title('data point visualization')

# Set x-axis label
plt.xlabel('X')

# Set y-axis label
plt.ylabel('Y')

TypeError: ignored

In [12]:
data_points = df.values

In [13]:
data_points

array([[9, 1],
       [3, 7],
       [2, 9]])

### Which point is the nearest from origin (0,0)?

In [14]:
linalg.norm(data_points, ord=2,axis=1)

array([9.05538514, 7.61577311, 9.21954446])

### L2 Norm  in Machine Learning

- kNN algorithm
- kmean algorithm

# source code in github

## https://github.com/minsuk-heo/python_tutorial