<a href="https://colab.research.google.com/github/redpineK/keras/blob/main/Vectorization_Implementation_in_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import numpy
import numpy as np

# define two numpy arrays
a = np.array([[1,2],[3,4]])
b = np.array([[1,1],[1,1]])

print(a)
print(b)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [3]:
# addition
print(a + b)

[[2 3]
 [4 5]]


In [4]:
# substraction
print(a - b)

[[0 1]
 [2 3]]


In [5]:
# multiplication:
print(a * b)

[[1 2]
 [3 4]]


In [6]:
# matrix multiplication
print(np.dot(a,b))

[[3 3]
 [7 7]]


In [7]:
# matrix product alternative
print(a@b)

[[3 3]
 [7 7]]


In [8]:
# numpy array with one row
a =  np.array([1,2,3])
print(a.shape)

(3,)


In [9]:
# numpy array with three rows
b = np.array([[1],[2],[3]])
print(b.shape)

(3, 1)


In [10]:
# Define an 3x3 2d array
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# select first element in the array
print(a[0,0])

1


In [12]:
# select first row of the array
print(a[0,:])

[1 2 3]


In [13]:
# select second coulumn of the array
print(a[:,1])

[2 5 8]
